mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', 'inventory.views.home', name='home'),

    url(r'^inventory/', 'inventory.views.display_inventory', name='inv'),    
    url(r'^category/(?P<cat_id>\d+)/$', 'inventory.views.display_category', name='cat'),
    url(r'^item/(?P<item_id>\d+)/edit/$', 'inventory.views.item_edit', name='item_edit'),
    url(r'^item/(?P<cat_id>\d+)/add_item/$', 'inventory.views.item_add', name='item_add'),
    url(r'^category/(?P<cat_id>\d+)/add/$', 'inventory.views.category_add', name='category_add'),
    url(r'^category/add/$', 'inventory.views.category_add_base', name='category_add_base'),
    url(r'^item/(?P<item_id>\d+)/get/$', 'inventory.views.item_qty_get', name='get_qty'),

    url(r'^blog/', 'blog.views.display_blog', name='blog'),
    url(r'^post/(?P<post_id>\d+)/$', 'blog.views.display_post', name='post'),
    url(r'^tag/(?P<tag>\w+)/$', 'blog.views.display_tag', name='tag'),

    url(r'^portfolio/', 'portfolio.views.display_portfolio', name='portfolio'),
    url(r'^(?P<study_id>\d+)/study/$', 'portfolio.views.display_study', name='study'),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.
class Poll(models.Model):
	author = models.CharField(max_length=60)
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def was_published_recently(self):
        	return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    	was_published_recently.admin_order_field = 'pub_date'
    	was_published_recently.boolean = True
    	was_published_recently.short_description = 'Published recently?'

	def __unicode__(self):
		return self.question

	def was_published_recently(self):
		now = timezone.now()
    		return now - datetime.timedelta(days=1) <= self.pub_date <  now
		
class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	answer = models.CharField(max_length=200)
	count = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.answer

polls/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """
	Return the last five published polls (not including those set to be
	published in the future).
	"""
	return Poll.objects.filter(
	    pub_date__lte=timezone.now()
	    ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any polls that aren't published yet.
        """
        return Poll.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
	p = get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#Redisplay the poll voting form
		return render(request, 'polls/detail.html', {
			'poll': p,
			'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.count += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
        	# with POST data. This prevents data from being posted twice if a
        	# user hits the Back button.
        	return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>Polls</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'polls/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="screen">

  </head>
  <body>
    <div class="container">
	<div class="bar"></div>
	<div class="nav">
		<a href="{% url 'home' %}" class="site">App List</a>
	</div>
	<a href="{% url 'polls:index' %}"><h1 class="text-center">Polls</h1></a>
	<h3 class="text-center">{{ poll.question }}</h3>
	<hr>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class="forms">
	<form action="{% url 'polls:vote' poll.id %}" method="post">
		{% csrf_token %}
		{% for choice in poll.choice_set.all %}
	    	    <input class="radio-inline" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	    	    <label class="label" for="choice{{ forloop.counter }}">{{ choice.answer }}</label><br />
		{% endfor %}
		<input type="submit" value="Vote" />
        </form>
	</div>
	<div class="bar"></div>
    </div><!-- /.container -->
	
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Polls</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'polls/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="screen">

  </head>
  <body>
    <div class="container">
	<div class="bar"></div>
	<div class="nav">
		<a href="{% url 'home' %}" class="site">App List</a>
	</div>
	<a href="{% url 'polls:index' %}"><h1 class="text-center">Polls</h1></a>
	<h3 class="text-center">Please select a poll you would like to vote in</h3>
	<hr>
	{% if latest_poll_list %}
	    <ul class="text-center unstyled">
	    {% for poll in latest_poll_list %}
		<h4><li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li></h4>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
	<div class="bar"></div>
    </div><!-- /.container -->
	
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <title>Polls</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'polls/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="screen">

  </head>
  <body>
    <div class="container">
	<div class="bar"></div>
	<div class="nav">
		<a href="{% url 'home' %}" class="site">App List</a>
	</div>
	<a href="{% url 'polls:index' %}"><h1 class="text-center">Polls</h1></a>
<h3 class="text-center">{{ poll.question }}</h3>
<hr>
<ul class="text-center unstyled">
{% for choice in poll.choice_set.all %}
    <h4><li>{{ choice.answer }} -- {{ choice.count }} vote{{ choice.count|pluralize }}</li></h4>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
<div class="bar"></div>
    </div><!-- /.container -->
	
</body>
</html>